<a href="https://colab.research.google.com/github/gan1014/Machine_learning-projects/blob/main/logistic_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [2]:
import pandas as pd
import numpy as np

# Load the Titanic training data
df = pd.read_csv("tested.csv")

df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [4]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [5]:
# Drop Cabin (too many missing values)
df.drop(columns=["Cabin"], inplace=True)

# Fill Age missing values with median
df["Age"].fillna(df["Age"].median(), inplace=True)

# Fill Fare missing value with median
df["Fare"].fillna(df["Fare"].median(), inplace=True)


/tmp/ipython-input-365622217.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipython-input-365622217.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try us

In [6]:
df.isnull().sum()


PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [7]:
df = df.drop(columns=["PassengerId", "Name", "Ticket"])
df.head()


Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [9]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"])
df["Embarked"] = le.fit_transform(df["Embarked"])

df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  34.5      0      0   7.8292         1
1         1       3    0  47.0      1      0   7.0000         2
2         0       2    1  62.0      0      0   9.6875         1
3         0       3    1  27.0      0      0   8.6625         2
4         1       3    0  22.0      1      1  12.2875         2

In [10]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

X.head(), y.head()


(   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
 0       3    1  34.5      0      0   7.8292         1
 1       3    0  47.0      1      0   7.0000         2
 2       2    1  62.0      0      0   9.6875         1
 3       3    1  27.0      0      0   8.6625         2
 4       3    0  22.0      1      1  12.2875         2,
 0    0
 1    1
 2    0
 3    0
 4    1
 Name: Survived, dtype: int64)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [14]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)


LogisticRegression(max_iter=1000)

In [15]:
y_pred = model.predict(X_test)
y_pred[:10]


array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [16]:
accuracy_score(y_test, y_pred)


1.0

In [17]:
confusion_matrix(y_test, y_pred)


array([[50,  0],
       [ 0, 34]])

In [18]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84



In [19]:
X.columns


Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [20]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [21]:
train_test_split(X, y, test_size=0.2, random_state=1)


[     Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
 337       3    1  39.0      0      2   7.2292         0
 224       1    0  53.0      0      0  27.4458         0
 376       3    0  22.0      2      0   8.6625         2
 312       3    1  27.0      0      0   7.5750         2
 165       3    0  26.0      1      1  22.0250         2
 ..      ...  ...   ...    ...    ...      ...       ...
 255       3    1  27.0      0      0   7.5500         2
 72        3    0  29.0      0      0   7.9250         2
 396       3    1  24.0      0      0   7.2500         1
 235       3    1  20.0      0      0   7.8542         2
 37        3    0  21.0      0      0   8.6625         2
 
 [334 rows x 7 columns],
      Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
 358       3    1  27.0      0      0    7.7500         1
 164       2    1  41.0      0      0   13.0000         2
 17        3    1  21.0      0      0    7.2250         0
 67        1    1  47.0      0      0   42.4000         2

In [22]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
y_pred = model.predict(X_test)
y_pred[:10]


array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0])

In [24]:
accuracy_score(y_test, y_pred)

1.0